### ISSUE TITLE
Echoing and degradation of sound quality as call proceeds

### ISSUE THREAD

**Issue by vendr-inc** [twilio/video-quickstart-swift#108] opened 2017-04-12 04:44 UTC
I am routing the audio from the call to the earpiece rather than the speakers - and am finding that as the call proceeds, the sound quality degrades into echoing. What could possibly be going wrong?

**Comment by ceaglest** [comment] 2017-04-14 03:26
Hi @vendr-inc,

Our mobile Video SDKs are based upon Chromium WebRTC, the same library that powers WebRTC communications in the Chrome browser. We've experienced echo cancellation issues pretty often in Chrome, but less so on iOS.

Is there a particular device or OS version that you are experiencing the problem on? Can you tell us anything else about the Participants and Media in your Rooms?

If you can reproduce the problem consistently a set of debug logs from the device would be helpful.

Best,
Chris

**Comment by vendr-inc** [comment] 2017-04-17 05:48
Hi there,

We are seeing this issue sporadically and randomly on iOS 10.2, iPhones 6Plus and 6. The track that was being used was your standard audio (not speakers).

It's hard to reproduce the issue because it happens so sporadically, but we will keep our eye out for it. It's still happening in betat14.

Thanks,
The Vendr Team

**Comment by ptankTwilio** [comment] 2017-07-13 04:44
@vendr-inc were you able to reproduce the problem. We have released TwilioVideo version 1.2.1 yesterday which is more stable. I encourage you to try version 1.2.1.

Regards,
Piyush

**Comment by ptankTwilio** [comment] 2017-07-17 20:08
@vendr-inc Closing the ticket as we are not able to reproduce the problem audio echo cancellation on iOS. Please re-open this ticket if you run into the issue again.

Thanks,
Piyush

**Closed by ptankTwilio** 2017-07-17 20:08 UTC
Labels: bug

**Comment by mdflores** [comment] 2018-06-07 09:04
I am experiencing this issue with iPhone 6 iOS 11.0.3. I am able to hear myself back from the phone speakers, call participants are on different rooms.

**Comment by piyushtank** [comment] 2018-06-08 07:09
@mdflores Thanks for reaching out. In order to help debug the problem -
- Can you provide the scenario details to reproduce the problem? 
- Are you observing problem in P2P or Group Room?
- What version of Twilio Video SDK are you using? 
- Are you able to reproduce the problem on our [Quickstart](https://github.com/twilio/video-quickstart-swift/tree/master/VideoQuickStart)?

**Comment by mdflores** [comment] 2018-06-08 13:51
During a call, when user speaks about 1.5s there would be a playback where you can hear what the user uttered. Note that the participants of the call are on different locations.

Steps to Reproduce
iOS Client 1 Connects to call via TwilioVideo SDK
iOS Client 2 Connects to call via TwilioVideo SDK
iOS Client 1 speaks to start.
Echo back from what the user spoke --> point of problem
Expected Behavior
During call, minimal or at least no echo when speaking.

Actual Behavior
During a call, when I speak there is an echo playing back what I have uttered

Reproduces How Often
100% Reproduced

Versions
All relevant version information for the issue.

Video iOS SDK
TwilioVideo (1.3.10) via CocoaPods

Xcode
Xcode 9.4

iOS Version
11.0.3

iOS Device
iPhone 6, iPhone 6 Plus

Will have to try with the QuickStart.
