### ISSUE TITLE
video view is not as usual

### ISSUE THREAD

**Issue by hxlonline** [twilio/video-quickstart-swift#139] opened 2017-06-09 02:40 UTC
(https://user-images.githubusercontent.com/18007116/26958727-30a96ac4-4d07-11e7-9219-c1a3d294a04c.jpeg)

This .jpeg is the view of video chat , why did this condition exist in the up-left of the view.how can I solve this problem.

**Comment by paynerc** [comment] 2017-06-09 20:26
Hi there,

I have reviewed the image you attached and am not certain I follow your question. 

A few things to help us get started:

1. What version of iOS are you running?
2. What is the device you are running on?
3. What version of the TwilioSDK are you consuming?
4. Can you provide a little more background into the configuration of your application? What is supposed to be displayed in the upper left? Are you connected to a room? Are other participants connected to the room?
5. Does the same situation occur when using the Quickstart application?

Looking forward to hearing back from you so we can resolve this issue.

Thanks!

Ryan

**Comment by hxlonline** [comment] 2017-06-12 05:23
Thank you for your response

1,iOS 10.3.2
2,iPhone
3,TwilioVideo1.0.0
4, when i was star to run  , it is no problem to work .but at few minutes ago ,  i saw the phenomenon like up-left of the picture
5,run the quickstart application have no problem in my tested several times;

**Comment by paynerc** [comment] 2017-06-13 16:02
Hello again!

When you refer to the phenomenon in the upper left corner, what is supposed to be being rendered there? Is that the local video track? If so, what are class are you using to render it? Does this problem happen with every room you join? 

Would it be possible to submit some sample code to show what is happening in a reproducible manner? 

Also, it would be helpful to examine the logs that are generated when this situation occurs. You can enable debug logging by adding a call to `TwilioVideo.setLogLevel(.debug)`.

If you would like to send the logs and/or sample project that reproduces the issue to me privately, you could create a support ticket by emailing support@twilio.com, attach the file(s) and reference me in the ticket; that will help get it routed to me directly.

Thank you,

Ryan

**Comment by ceaglest** [comment] 2017-06-27 19:46
Hi @hxlonline,

Any more updates on this issue? We'd like to help out but don't have enough information to proceed.

Regards,
Chris

**Comment by ceaglest** [comment] 2017-07-01 22:07
Closing due to lack of information.

**Closed by ceaglest** 2017-07-01 22:07 UTC
