### ISSUE TITLE
[MTLDebugRenderCommandEncoder setRenderPipelineState:]:1298: failed assertion `renderPipelineState must not be nil.

### ISSUE THREAD

**Issue by raakshash** [twilio/video-quickstart-swift#288] opened 2018-07-05 10:25 UTC
### Description

I have been trying to migrate my ios application to sdk 11.4 and using the existing metal api. After application launch in iPad through xCode, I got a white screen and an error indicating that renderPipelineState must not be nill. Here is the code which has been failing:

`id<MTLRenderCommandEncoder> cEncoder = _context.GetCurrentRenderEncoder();
[cEncoder setRenderPipelineState:quadShader->GetRenderPipelineState( SQShaderMetal::BE_StandardAlphaBlend, &_context )];`

After analyzing more I found that some MetalQuad library has not been opened successfully and that code have been failed with an error. Here is the code to open MetalQuad library
<img width="1298" alt="screen shot 2018-07-05 at 3 45 18 pm" src="https://user-images.githubusercontent.com/13520509/42317650-7f1e2ad6-806a-11e8-95d1-e10d3aa6ecf7.png">

In the above image iMTLLibraryData is MetalQuad.metallib libary, which eventually not gives any new library for a MTLDevice and gives error that this format is not supported or built on old tools.

#### Reproduces How Often

Everytime

#### Xcode

xCode 9.4

#### iOS Version

iOS SDK 11.4

#### iOS Device

iPad pro

**Comment by piyushtank** [comment] 2018-07-10 03:09
@raakshash Sorry for being late in responding back. In order to debug the problem further, can you provide following information -
1. Twilio Video SDK version
2. Is it possible for you to explain the used case you are trying to achieve?
3. Are you writing your custom renderer using TVIVideoRenderer APIs? Please note that the video SDK provides Metal and OpenGL ES renderer by default, but you are free to write your own custom renderer.

**Comment by raakshash** [comment] 2018-07-10 11:37
@piyushtank I am not sure regarding the renderer. also I dont have any used cases.
But as I see that my application is not running further because of this error.

Also one thing that we are using a custom code builder which uses command line tool with some options
<img width="785" alt="screen shot 2018-07-10 at 5 04 53 pm" src="https://user-images.githubusercontent.com/13520509/42507634-79228ddc-8463-11e8-83de-eba385016116.png">

is possible that due to code builder this problem is coming? Also if the options given with the metal command are old then will it build the metal APIs in old format? Because the error is saying that the library format is not supported on the platform or build with old version of the tool

**Comment by piyushtank** [comment] 2018-07-16 19:18
@raakshash It is very hard to debug the problem without knowing what you are trying to achieve using video sdk. Are you able to reproduce the problem on our sample app?

**Comment by ceaglest** [comment] 2018-08-23 19:00
Hi @raakshash,

From the discussion so far, you don't appear to be using `TVIVideoView`, but rather your own Metal renderer. Are you looking for advice on how to solve a problem in your application renderer code? If so, please provide the source code for at least the renderer (if not a runnable version of the app) and we will do our best to help.

I'm closing this ticket, because its not actionable at this time. If you have more information to share please feel free to reopen this issue.

Thanks,
Chris

**Closed by ceaglest** 2018-08-23 19:00 UTC
Labels: question
