### ISSUE TITLE
Showing black screen for some seconds

### ISSUE THREAD

**Issue by sathishvgs** [twilio/video-quickstart-swift#214] opened 2018-01-08 15:01 UTC
Hi,
      I'm using twilio programmable video in my iOS Application. After the Call connected, it shows the black screen for 15-20 seconds. I tried to resolve this issue but I couldn't find the appropriate solution. Can anyone give a valid solution. 

```  
   func subscribed(to videoTrack: TVIRemoteVideoTrack, publication: TVIRemoteVideoTrackPublication, for participant: TVIRemoteParticipant) {
          if !participant.remoteVideoTracks.isEmpty {
                participant.remoteVideoTracks[0].remoteTrack?.addRenderer(self.getRemoteView())
           }
  }

**Comment by ptankTwilio** [comment] 2018-01-08 19:22
@sathishvgs Thanks for reaching out. Can you provide following information to help debug this problem : 
1. Device and iOS version 
2. Video SDK version
3. Are you able to reproduce the problem on [QuickStart sample app](https://github.com/twilio/video-quickstart-swift) ?

**Comment by sathishvgs** [comment] 2018-01-09 11:46
@ptankTwilio yeah sure.
1. Device : Iphone 5s 
   iOS Version: 11.2

2. Video SDK: 2.0.0-preview7

3. I will test with QuickStart and update here

4. Room SID : RMd2979dd030960cd2174daa1a549bb59a

**Comment by ceaglest** [comment] 2018-01-13 01:05
Hi @sathishvgs,

I took a look at the Room traffic. I see the first Participant (P1) joining a VP8 Group Room, and its Audio Track being enabled and disabled repeatedly. Next, (15s later) P2 joins. Both P1 and P2 subscribe to each other's media very quickly after P2 connects and ICE becomes connected within the first 3 seconds. Each participant subscribes and publishes to several MB of media during the time they are in the Room.

Are you receiving the subscription callback for the video Track right away, or not at all? We did notice an occasional issue which caused subscription callbacks to be missed in `2.0.0-preview7` which was fixed in `2.0.0-preview8`.

Also, you wrote:

```
   func subscribed(to videoTrack: TVIRemoteVideoTrack, publication: TVIRemoteVideoTrackPublication, for participant: TVIRemoteParticipant) {
          if !participant.remoteVideoTracks.isEmpty {
                participant.remoteVideoTracks[0].remoteTrack?.addRenderer(self.getRemoteView())
           }
  }
```

Which should work, but you could make this a little bit simpler:

```.swft
func subscribed(to videoTrack: TVIRemoteVideoTrack, publication: TVIRemoteVideoTrackPublication, for participant: TVIRemoteParticipant) {
      videoTrack.addRenderer(self.getRemoteView())
}
```

Here is a summary of the traffic for the Room.

```
Summary for room name: testA | sid: RMd2979dd030960cd2174daa1a549bb59a | account sid: ACxxx
Topology: group | Adhoc: True | TURN: True | Recording: False | Video Codecs: VP8 | Media Region: us1
Participants:
P2: name: 0066a74a-1285-4998-a67b-61aeafd417fa | sid: PAf60a6460b2250c89a3e868ca2c8aac84 | call sid: CAeca79e5f1bf98fa3276195b979d1d2ad | sdp format: Plan B
P1: name: 03e30e43-1762-4e71-a273-68f6484b8955 | sid: PAa3ec7c28614ec96b92ff3373abf3eb3d | call sid: CA1d677f345926e46d918bda47c09f06a6 | sdp format: Plan B
2018-01-09T09:44:45.428Z: [add_labeled_room]
2018-01-09T09:44:45.428Z: P1 sent connect with audio + video tracks
2018-01-09T09:44:45.428Z: P1 sent offer for peer connection id d5070b84-b780-4841-9da0-f75863688a70 revision: 1
2018-01-09T09:44:45.428Z: [room_created]
2018-01-09T09:44:45.828Z: P1 received connected
2018-01-09T09:44:45.828Z: P1 received answer for peer connection id d5070b84-b780-4841-9da0-f75863688a70 revision: 1
2018-01-09T09:44:45.828Z: P1 published video track name: d6d12eaf-da8f-44c3-80d6-61e46f8e00eb sid: MTc5c17265df220de751c09d686b1761c5 revision: 1
2018-01-09T09:44:45.828Z: P1 published audio track name: 8bb255ba-3232-436b-800d-9eb254c6cdd6 sid: MTaa5596d1abf49de38d2bef86b8eff547 revision: 1
2018-01-09T09:44:46.479Z: P1 sent ice complete for peer connection id d5070b84-b780-4841-9da0-f75863688a70 with 5 ice candidates [ 4 host, 1 srflx, 0 relay ] revision: 6
2018-01-09T09:44:46.479Z: P1 sent update with track changes: audio was muted revision: 4
2018-01-09T09:44:46.857Z: P1 sent update with track changes: audio was unmuted revision: 5
2018-01-09T09:44:47.148Z: P1 sent update with track changes: audio was muted revision: 6
2018-01-09T09:44:47.762Z: [ice_connection_state_change] for P1 with state CONNECTED
2018-01-09T09:44:47.762Z: [ice_connection_state_change] for P1 with state COMPLETED
2018-01-09T09:45:00.261Z: P2 sent connect with audio + video tracks
2018-01-09T09:45:00.261Z: P2 sent offer for peer connection id 7C8ACd95C19EAEeE864CD0124D956D6b revision: 1
2018-01-09T09:45:00.282Z: P2 received connected
2018-01-09T09:45:00.282Z: P2 received answer for peer connection id 7C8ACd95C19EAEeE864CD0124D956D6b revision: 1
2018-01-09T09:45:00.282Z: P2 published audio track name: ac2Bb9709e51dCc3A75D970caBbE3CD5 sid: MT193f280bead49647d0885987a4cb437a revision: 1
2018-01-09T09:45:00.282Z: P2 published video track name: 25A0651DDd3CFf96A30aeCffff64A69a sid: MT823dd04f3b60c218b6b8b1b5c81c3e89 revision: 1
2018-01-09T09:45:00.283Z: P1 received offer for peer connection id d5070b84-b780-4841-9da0-f75863688a70 revision: 2
2018-01-09T09:45:00.283Z: P1 subscribed to track sid: MT823dd04f3b60c218b6b8b1b5c81c3e89 revision: 2
2018-01-09T09:45:00.283Z: P1 subscribed to track sid: MT193f280bead49647d0885987a4cb437a revision: 2
2018-01-09T09:45:00.283Z: P2 received offer for peer connection id 7C8ACd95C19EAEeE864CD0124D956D6b revision: 2
2018-01-09T09:45:00.283Z: P2 subscribed to track sid: MTaa5596d1abf49de38d2bef86b8eff547 revision: 2
2018-01-09T09:45:00.283Z: P2 subscribed to track sid: MTc5c17265df220de751c09d686b1761c5 revision: 2
2018-01-09T09:45:00.801Z: P1 sent answer for peer connection id d5070b84-b780-4841-9da0-f75863688a70 revision: 2
2018-01-09T09:45:00.805Z: [ice_connection_state_change] for P1 with state CONNECTED
2018-01-09T09:45:03.142Z: P2 sent ice complete for peer connection id 7C8ACd95C19EAEeE864CD0124D956D6b with 5 ice candidates [ 2 host, 1 srflx, 2 relay ] revision: 6
2018-01-09T09:45:03.142Z: P2 sent answer for peer connection id 7C8ACd95C19EAEeE864CD0124D956D6b revision: 2
2018-01-09T09:45:03.403Z: [ice_connection_state_change] for P2 with state CONNECTED
2018-01-09T09:45:09.247Z: P1 sent update with track changes: audio was unmuted revision: 7
2018-01-09T09:45:13.342Z: P1 sent update with track changes: audio was muted revision: 8
2018-01-09T09:45:13.514Z: [ice_connection_state_change] for P1 with state COMPLETED
2018-01-09T09:45:15.866Z: [ice_connection_state_change] for P2 with state COMPLETED
2018-01-09T09:45:41.590Z: P2 sent update with track changes: video was paused revision: 4
2018-01-09T09:45:41.928Z: P2 sent disconnect
2018-01-09T09:45:41.931Z: P2 received disconnected
2018-01-09T09:45:41.935Z: P1 received offer for peer connection id d5070b84-b780-4841-9da0-f75863688a70 revision: 3
2018-01-09T09:45:41.936Z: [group_billing_event] for P2 with bytes sent 2678144, bytes received 5923608
2018-01-09T09:45:42.343Z: P1 sent answer for peer connection id d5070b84-b780-4841-9da0-f75863688a70 revision: 3
2018-01-09T09:45:42.349Z: [ice_connection_state_change] for P1 with state CONNECTED
2018-01-09T09:45:55.056Z: [ice_connection_state_change] for P1 with state COMPLETED
2018-01-09T09:45:56.951Z: P1 sent disconnect
2018-01-09T09:45:56.954Z: P1 received disconnected
2018-01-09T09:45:56.955Z: [group_billing_event] for P1 with bytes sent 5961374, bytes received 4540123
2018-01-09T09:45:56.958Z: [delete_labeled_room]
```

Let me know how I can help. In this case I think you might have just been victim to a bug in `2.0.0-preview7` which has since been fixed.

Best,
Chris Eagleston

**Comment by sathishvgs** [comment] 2018-01-18 03:45
Hi @ceaglest ,
                         I have tried with updating to 2.0.0-preview8 but still its showing black screen. Can you explain why the audio is enabled and disabled frequently.

**Comment by sathishvgs** [comment] 2018-01-30 16:08
Hi @ceaglest @piyushtank , 
          If I use the 2.0.0-preview8, the audio track[local and remote audio track] is not working most of time. But, if I try with 2.0.0-preview4, the audio track is working fine. Can you guys explain why its happening.

**Comment by ceaglest** [comment] 2018-01-30 16:37
Hi @sathishvgs,

Sorry for not responding to your earlier comment.

> I have tried with updating to 2.0.0-preview8 but still its showing black screen. Can you explain why the audio is enabled and disabled frequently.

Audio should not be enabled and disabled unless you explicitly toggle the `enabled` property of the Track. Is there something in your application code that modifies the property?

It would be great if you could let us know if this issue is reproducible in the QuickStart app (especially with the latest 2.0.0-preview9 release). As a reference application it handles all audio related delegate callbacks using best practices. As always, if you give us a Room SID where you're having issues we will do our best to diagnose and fix the problem.

Regards,
Chris Eagleston

**Comment by sathishvgs** [comment] 2018-02-03 09:51
Hi @ceaglest @piyushtank  This is my Room Sid ->  RMa984beebdaafb5260ea423f04915194c . Can you check it why the audioTrack is not working.

**Comment by piyushtank** [comment] 2018-02-04 23:40
@sathishvgs We will look it up the Room's traffic however it will be helpful debug the problem if you could answer Chris' questions asked in his last reponse  - 

> Audio should not be enabled and disabled unless you explicitly toggle the enabled property of the Track. Is there something in your application code that modifies the property?

> It would be great if you could let us know if this issue is reproducible in the QuickStart app (especially with the latest 2.0.0-preview9 release). As a reference application, it handles all audio related delegate callbacks using best practices.

**Comment by sathishvgs** [comment] 2018-02-05 13:23
Hi @piyushtank ,
         I tried in QuickStart app, it worked fine. In my application, I'm trying with multi participant call and following the same for localAudioTrack. Can you show the logs for the above Room sid.

**Comment by ceaglest** [comment] 2018-02-07 07:48
Hey @sathishvgs,

Thanks for the Room SID. I pulled the traffic and there are a couple of things to note:

```
Summary for room name: test | sid: RMa984beebdaafb5260ea423f04915194c | account sid: ACxxx
Topology: group | Adhoc: True | TURN: True | Recording: False | Video Codecs: VP8 | Media Region: us1
VMS sid: VMxxx
Participants:
P1: name: c5dd528a-5ac9-41d6-9650-2fcf21f3d712 | sid: PA83a1904ef34b47e85ecf0a7f1e042d4e | call sid: CAeb2b9251f0be5b7d5b25fbcca101e8d7 | sdp format: Plan B
P2: name: 45b35fc7-c2f3-41d7-9e2a-d0609c6a2aad | sid: PA0431a7cca683f8a8c2c990980027ba25 | call sid: CAe79cd03b6d30e0e227732aa2a8dc7377 | sdp format: Plan B
```

1. I can see in the logs that P1 performs a `sync`. You may have noticed that media did not return after this, which is due to https://github.com/twilio/video-quickstart-swift/issues/154. After syncing P1 also mutes/disables their video. Are you toggling the `LocalVideoTrack.enabled` property here?

2. Once P2 connects the Participants subscribe to each other's Audio and Video tracks pretty quickly.

3. Several MB of Data is exchanged between the Participants.

Did you hear audio only for the first portion of the Room, and not after the `sync` event, or never at all?

4. If you're outside of North America you should consider using our Media Regions API to select a media server nearer to your Participants. You can read up on creating Rooms via REST [here](https://www.twilio.com/docs/api/video/rooms-resource
) and see a list of the regions that we support [here](https://www.twilio.com/docs/api/video/ip-address-whitelisting#group-rooms-media-servers).

```
2018-02-03T09:47:48.361Z: P1 sent connect with audio + video tracks
2018-02-03T09:47:48.361Z: P1 sent offer for peer connection id 90f4ca95-e65b-ccb7-b76a-c4cbbe05b530 revision: 1
2018-02-03T09:47:48.362Z: [add_labeled_room]
2018-02-03T09:47:48.364Z: [room_created]
2018-02-03T09:47:49.246Z: P1 received connected
2018-02-03T09:47:49.246Z: P1 received answer for peer connection id 90f4ca95-e65b-ccb7-b76a-c4cbbe05b530 revision: 1
2018-02-03T09:47:49.246Z: P1 published video track name: 41869becd8ca91470469d1e5ed6905457b9f sid: MTe268d116e23de72b77f7b3973c4ca348 revision: 1
2018-02-03T09:47:49.246Z: P1 published audio track name: a11ca5f9148f94f3385ffbddc2a35bb8912e sid: MT313eb6d1b2f05aa9f404baab0389b27f revision: 1
2018-02-03T09:47:50.255Z: P1 sent ice complete for peer connection id 90f4ca95-e65b-ccb7-b76a-c4cbbe05b530 with 3 ice candidates [ 2 host, 1 srflx, 0 relay ] revision: 4
2018-02-03T09:47:51.314Z: [ice_connection_state_change] for P1 with state CONNECTED
2018-02-03T09:47:51.314Z: [ice_connection_state_change] for P1 with state COMPLETED
2018-02-03T09:48:17.076Z: P2 sent connect with audio + video tracks
2018-02-03T09:48:17.076Z: P2 sent offer for peer connection id f6aB1fa7Bbee74D2B0D05da19E451e1f revision: 1
2018-02-03T09:48:17.095Z: P2 received connected
2018-02-03T09:48:17.095Z: P2 received answer for peer connection id f6aB1fa7Bbee74D2B0D05da19E451e1f revision: 1
2018-02-03T09:48:17.095Z: P2 published video track name: micvideo sid: MTc9a81cebf468aad0a96cbbdd699f5470 revision: 1
2018-02-03T09:48:17.095Z: P2 published audio track name: ECABf8e1D1A9DBFe423f28B65EE74636 sid: MTda10801deba5371729da745e4817a171 revision: 1
2018-02-03T09:48:17.096Z: P1 received offer for peer connection id 90f4ca95-e65b-ccb7-b76a-c4cbbe05b530 revision: 2
2018-02-03T09:48:17.096Z: P1 subscribed to track sid: MTda10801deba5371729da745e4817a171 revision: 2
2018-02-03T09:48:17.096Z: P1 subscribed to track sid: MTc9a81cebf468aad0a96cbbdd699f5470 revision: 2
2018-02-03T09:48:17.096Z: P2 received offer for peer connection id f6aB1fa7Bbee74D2B0D05da19E451e1f revision: 2
2018-02-03T09:48:17.096Z: P2 subscribed to track sid: MTe268d116e23de72b77f7b3973c4ca348 revision: 2
2018-02-03T09:48:17.096Z: P2 subscribed to track sid: MT313eb6d1b2f05aa9f404baab0389b27f revision: 2
2018-02-03T09:48:17.929Z: P2 sent ice complete for peer connection id f6aB1fa7Bbee74D2B0D05da19E451e1f with 3 ice candidates [ 1 host, 1 srflx, 1 relay ] revision: 4
2018-02-03T09:48:17.929Z: P2 sent answer for peer connection id f6aB1fa7Bbee74D2B0D05da19E451e1f revision: 2
2018-02-03T09:48:20.473Z: [ice_connection_state_change] for P2 with state CONNECTED
2018-02-03T09:48:21.364Z: P1 sent answer for peer connection id 90f4ca95-e65b-ccb7-b76a-c4cbbe05b530 revision: 2
2018-02-03T09:48:21.371Z: [ice_connection_state_change] for P1 with state CONNECTED
2018-02-03T09:48:30.638Z: [ice_connection_state_change] for P2 with state COMPLETED
2018-02-03T09:48:34.072Z: [ice_connection_state_change] for P1 with state COMPLETED
2018-02-03T09:49:20.627Z: P1 sent sync
2018-02-03T09:49:20.627Z: P1 sent ice complete for peer connection id 90f4ca95-e65b-ccb7-b76a-c4cbbe05b530 with 3 ice candidates [ 2 host, 1 srflx, 0 relay ] revision: 4
2018-02-03T09:49:20.627Z: P1 sent answer for peer connection id 90f4ca95-e65b-ccb7-b76a-c4cbbe05b530 revision: 2
2018-02-03T09:49:20.629Z: P1 received synced
2018-02-03T09:49:20.629Z: P1 received offer for peer connection id 90f4ca95-e65b-ccb7-b76a-c4cbbe05b530 revision: 2
2018-02-03T09:49:20.935Z: P1 sent offer for peer connection id 90f4ca95-e65b-ccb7-b76a-c4cbbe05b530 revision: 3
2018-02-03T09:49:20.943Z: P1 received answer for peer connection id 90f4ca95-e65b-ccb7-b76a-c4cbbe05b530 revision: 3
2018-02-03T09:49:22.424Z: [ice_connection_state_change] for P1 with state CONNECTED
2018-02-03T09:49:22.712Z: [ice_connection_state_change] for P1 with state COMPLETED
2018-02-03T09:49:22.744Z: P1 sent ice complete for peer connection id 90f4ca95-e65b-ccb7-b76a-c4cbbe05b530 with 5 ice candidates [ 2 host, 1 srflx, 2 relay ] revision: 6
2018-02-03T09:49:49.211Z: P1 sent update with track changes: video was paused revision: 4
2018-02-03T09:49:49.215Z: P1 published video track name: 41869becd8ca91470469d1e5ed6905457b9f sid: MTe268d116e23de72b77f7b3973c4ca348 revision: 2
2018-02-03T09:49:49.215Z: P1 published audio track name: a11ca5f9148f94f3385ffbddc2a35bb8912e sid: MT313eb6d1b2f05aa9f404baab0389b27f revision: 2
2018-02-03T09:49:49.925Z: P1 sent disconnect
2018-02-03T09:49:49.928Z: P1 received disconnected
2018-02-03T09:49:49.930Z: [group_billing_event] for P1 with bytes sent 3200607, bytes received 11885346, recording time in secs 0
2018-02-03T09:49:49.930Z: P2 received offer for peer connection id f6aB1fa7Bbee74D2B0D05da19E451e1f revision: 3
2018-02-03T09:49:50.498Z: P2 sent disconnect
2018-02-03T09:49:50.500Z: P2 received disconnected
2018-02-03T09:49:50.503Z: [group_billing_event] for P2 with bytes sent 6450078, bytes received 2910135, recording time in secs 0
2018-02-03T09:49:50.506Z: [delete_labeled_room]
```

Regards,
Chris

**Comment by sathishvgs** [comment] 2018-02-14 11:53
@ceaglest Thank you for your kindly help. I have fixed my issue. It happened because of the callkit. Now, its working fine.

**Comment by ceaglest** [comment] 2018-02-14 17:26
Great to hear @sathishvgs! I'll close out this ticket if everything is working for you.

**Closed by ceaglest** 2018-02-14 17:26 UTC
Labels: question

**Comment by adamrhunter** [comment] 2018-02-14 20:07
@sathishvgs  - I'm having similar problems with a black video screen being shown.  What was the change that you made that fixed the problem?

**Comment by sathishvgs** [comment] 2018-02-16 09:38
Hi @adamrhunter  
         For me, Audio Track problem is only fixed. Black video screen is still showing.

**Comment by Balasnest** [comment] 2020-06-30 11:40
I'm having similar issue. Black Screen appears even after participant video track delegates are called. What would be the issue?

It's happening in android and iOS devices. There is a huge delay after the participant connected.
In iOS, it's taking more time **(10 sec -2 mins)** to display participant video (participant is already joined from the android device)

Reference:
![Screenshot_20200624-224816](https://user-images.githubusercontent.com/6050520/86121841-60615700-baf4-11ea-89ce-50bca776c514.jpg)


More details:
User 1 - Codec: VP8
User 2 - Platform: iOS SDK Version: TwilioVideo', '~> 3.2.3' and com.twilio:video-android:5.5.0 codec: ios: H246 and android: VP8

In User 2, User 1 video is coming blank and sometime taking more time to display as well. Will there any conflicts with different SDK Version?

[log.txt](https://github.com/twilio/video-quickstart-ios/files/4851492/log.txt)


@ceaglest can you please help here. Any workaround for this?

**Comment by Balasnest** [comment] 2020-06-30 16:25
Similar issue related to android:
[ios - 536
](https://github.com/twilio/video-quickstart-android/issues/536)
Similar issue related to RN:
[RN - 94](https://github.com/blackuy/react-native-twilio-video-webrtc/issues/94)

**Comment by Balasnest** [comment] 2020-07-05 04:42
Please open this ticket! This is not yet resolved.
