### ISSUE TITLE
Issue rendering TVILocalVideoTrack in UICollectionViewCell

### ISSUE THREAD

**Issue by louiss98** [twilio/video-quickstart-swift#161] opened 2017-08-26 04:28 UTC
Hello,
I am building a group video chat application using the programmable video api, and I'm noticing some strange behavior when connecting to a room.

My goal was to render each room participant in a UICollectionViewCell as opposed to creating a UIView for each participant.

The following best describes my approach.

At the View Controller:

Initialize both the TVILocalVideoTrack & TVILocalAudioTrack
```swift
    func prepareLocalMedia() {
        
        // Create an audio track.
        if (localAudioTrack == nil) {
            localAudioTrack = TVILocalAudioTrack.init()
            
            if (localAudioTrack == nil) {
                print("audio track failed to initialize")
            }
        }
        
        // Create a video track which captures from the camera.
        if (localVideoTrack == nil) {
            let videoConstraints = TVIVideoConstraints { (constraints) in
                constraints.aspectRatio = TVIAspectRatio16x9
                constraints.maxFrameRate = 30
                constraints.minFrameRate = TVIVideoConstraintsFrameRateNone
            }
            
            camera = TVICameraCapturer(source: .frontCamera, delegate: self)
            localVideoTrack = TVILocalVideoTrack.init(capturer: camera!, enabled: true, constraints: videoConstraints)
            
            createRoom()
        }
    }
```

Connect to a room.
```swift
    func createRoom() {
        
        if (accessToken == "TWILIO_ACCESS_TOKEN") {
            do {
                accessToken = try TokenUtils.fetchToken(url: tokenUrl)
            } catch {
                print("Failed to fetch access token")
                return
            }
        }
        
        let connectOptions = TVIConnectOptions.init(token: accessToken) { (builder) in
            builder.audioTracks = [self.localAudioTrack!]
            builder.videoTracks = [self.localVideoTrack!]
            builder.roomName = "Test"
        }
        room = TwilioVideo.connect(with: connectOptions, delegate: self)
        print("attempting to connect to room Test")
        
        DispatchQueue.main.async(execute: {
            self.collectionView?.reloadData()
        })
    } 
```

At the UICollectionViewCell:
```swift
    func startPreview() {
        let videoConstraints = TVIVideoConstraints { (constraints) in
            constraints.aspectRatio = TVIAspectRatio16x9
            constraints.maxFrameRate = 30
            constraints.minFrameRate = TVIVideoConstraintsFrameRateNone
        }
        
        camera = TVICameraCapturer(source: .frontCamera, delegate: nil)
        
        localVideoTrack = TVILocalVideoTrack.init(capturer: camera!, enabled: true, constraints: videoConstraints)
        if (localVideoTrack == nil) {
            print("Video track in cell is nil")
        } else {
            localVideoTrack!.addRenderer(previewView)
            print("Video track added to previewView in Cell")
        }
    }
```

At cellForItemAt indexPath:

```swift

//Here I set the delegate for the TVICameraCapturer and TVIVideoView for the cell
                memberCell.previewView.delegate = self
                memberCell.camera.delegate = self
```

Currently what I expect is for a preview to render in the cell and also on the other participants screen.

What's actually happening is, as if by  random, the preview either renders solely on the device and no video data is sent to the room or video is sent to the room but doesn't render on the device.

Currently I am using TwilioVideo 1.3.2

Any suggestions?

**Comment by ptankTwilio** [comment] 2017-09-06 00:30
@louiss98 I apologize for responding late to you question.

An app should not create more than one local video track with camera as source. From the code snippet you have posted, it seems like two `localVideoTrack`s are created : the one while connecting to a Room and another one`UICollectionViewCell`'s  startPreview method.  Can you try creating a local video track and share it in your application?


Here is the modified methods  :
```swift
    func prepareLocalMedia() {
        
        // Create an audio track.
        if (localAudioTrack == nil) {
            localAudioTrack = TVILocalAudioTrack.init()
            
            if (localAudioTrack == nil) {
                print("audio track failed to initialize")
            }
        }
        
        // Create a video track which captures from the camera.
        if (localVideoTrack == nil) {
            let videoConstraints = TVIVideoConstraints { (constraints) in
                constraints.aspectRatio = TVIAspectRatio16x9
                constraints.maxFrameRate = 30
                constraints.minFrameRate = TVIVideoConstraintsFrameRateNone
            }
            
            camera = TVICameraCapturer(source: .frontCamera, delegate: self)
            localVideoTrack = TVILocalVideoTrack.init(capturer: camera!, enabled: true, constraints: videoConstraints)
        }

        createRoom()
    }

    func startPreview() {
        
        // Create a local video track if it it is not created yet
        if (localVideoTrack == nil) {
            let videoConstraints = TVIVideoConstraints { (constraints) in
                constraints.aspectRatio = TVIAspectRatio16x9
                constraints.maxFrameRate = 30
                constraints.minFrameRate = TVIVideoConstraintsFrameRateNone
            }
        
            camera = TVICameraCapturer(source: .frontCamera, delegate: nil)
        
            localVideoTrack = TVILocalVideoTrack.init(capturer: camera!, enabled: true, constraints: videoConstraints)
        }

        // Add renderer on the local video track
        if (localVideoTrack == nil) {
            print("Video track in cell is nil")
        } else {
            localVideoTrack!.addRenderer(previewView)
            print("Video track added to previewView in Cell")
        }
    }

**Comment by ptankTwilio** [comment] 2017-10-04 21:28
@louiss98 Hoping the problem is resolved at your end. I am closing the ticket but feel free to re-open if you observer the issue again.

**Closed by ptankTwilio** 2017-10-04 21:28 UTC
Labels: help wanted
