### ISSUE TITLE
Incoming call when app killed

### ISSUE THREAD

**Issue by hasgar** [twilio/video-quickstart-swift#234] opened 2018-03-08 01:43 UTC
Is it possible to get incoming call when app is killed?
I think user must have to push notification need to trigger another action inside the app.that doesn’t make incoming call like feeling in callkit..am i missing something?

**Comment by ceaglest** [comment] 2018-03-08 04:45
Hey @hasgar,

If you want to receive incoming calls then you should combine VoIP Push Notifications to wake up your app, with CallKit to grab control of the User's device and present the Call UI. Our [CallKit](https://github.com/twilio/video-quickstart-swift/tree/master/VideoCallKitQuickStart) QuickStart shows you how to do the CallKit part, but without push.

For more about using incoming pushes you should see this issue:
https://github.com/twilio/video-quickstart-swift/issues/147

We don't have a full push notification + CallKit example just yet, but we're considering adding one similar to the VideoInvite [example](https://github.com/twilio/video-quickstart-android/tree/master/exampleVideoInvite) the Android team has built.

Best,
Chris

**Comment by hasgar** [comment] 2018-03-08 09:19
@ceaglest Thank you

**Comment by ceaglest** [comment] 2018-03-14 19:30
No problem @hasgar. 

I hope you've got the information you need to proceed with your app. I'm going to close this one out given the linked issues which also cover this question.

**Closed by ceaglest** 2018-03-14 19:30 UTC
Labels: help wanted

**Comment by VDPurohit** [comment] 2018-10-18 06:12
Hello @ceaglest 

I was implementing text,audio and video chat so is it possible to we can use same voIP  certificate which generated  from "developer.apple.com" for audio as well as video?

**Comment by wazzah-marham** [comment] 2021-04-13 16:20
Hi @ceaglest I have used CallKit in IOS for this purpose and it is working fine.
But the problem is that in some of the Android devices you don't get notifications when the app is killed forcefully, how can I handle that scenario? And how to get Display Over Other Apps permission by default without having to show the prompt?

**Comment by hasancanbayram** [comment] 2022-11-28 12:50
did you get notification when app is killer by callee? i use agora for video call but cant receive notification when app is not running

**Comment by wazzah-marham** [comment] 2022-11-28 16:54
@hasancanbayram are you using Firebase for push? If yes then phones like Redmi and OPPO kill firebase service when the app is forcefully killed hence you don't get a push notification. But it works fine on Samsung devices.

But recently I worked on it again but I was getting the notification even if the app was forcefully killed, though they got delivered with delay but it worked.

**Comment by hasancanbayram** [comment] 2022-11-30 12:28
@wazzah-marham i use Firebase but i cannot send request from device, is it possible to do this. I have check all the videos about Firebase and they always send the notification from Firebase Console.

**Comment by wazzah-marham** [comment] 2022-11-30 12:46
@hasancanbayram I am sending push notifications from our server which is also the recommended approach. Device tokens are linked with userId in our database.

But if you want to send it from an android device please look at the article below:
https://medium.com/mindorks/send-device-to-device-push-notification-using-firebase-cloud-messaging-without-using-external-769476c79ffd
