### ISSUE TITLE
Getting black screen for some seconds before rendering the Remote videotrack

### ISSUE THREAD

**Issue by sathishvgs** [twilio/video-quickstart-swift#240] opened 2018-03-14 10:52 UTC
Hi,
      Before rendering the Remote videotrack, the video screen showing the black screen for more than 10 seconds. I already open this  #214 issue and  closed. 

This same issue occurred in Android also but now they have fixed it.
Reference: https://github.com/twilio/video-quickstart-android/issues/218

**Comment by paynerc** [comment] 2018-03-14 13:08
@sathishvgs,

When subscribing to a `TVIRemoteVideoTrack`, you need to wait for the [`subscribedToVideoTrack:publication:forParticipant:`](https://twilio.github.io/twilio-video-ios/docs/2.0.0-beta2/Protocols/TVIRemoteParticipantDelegate.html#//api/name/subscribedToVideoTrack:publication:forParticipant:) call back to alert you that you are indeed subscribe to the video track and that data will be forth coming.

When you create your [`TVIVideoView`](https://twilio.github.io/twilio-video-ios/docs/2.0.0-beta2/Classes/TVIVideoView.html), are you also setting a [`TVIVideoViewDelegate`](https://twilio.github.io/twilio-video-ios/docs/2.0.0-beta2/Classes/TVIVideoView.html#//api/name/delegate)?

Once the first frame is received, we will call [`videoViewDidReceiveData:`](https://twilio.github.io/twilio-video-ios/docs/2.0.0-beta2/Protocols/TVIVideoViewDelegate.html#//api/name/videoViewDidReceiveData:) which you can use to make the view visible, or what not. If you wait for this call back to be fired, you should not render any black frames.

You can also query [`hasVideoData`](https://twilio.github.io/twilio-video-ios/docs/2.0.0-beta2/Classes/TVIVideoView.html#//api/name/hasVideoData) to determine whether frames have been received for this view yet. 

A known limitation in our current implementation of `TVIVideoView`, however, is that if you reuse the view by adding it as a renderer to a different `TVIVideoTrack`, the `hasVideoData` property will not be reset and no `videoViewDidReceiveData:` will be sent. We are discussing options to improve this user experience so that you could reuse the same `TVIVideoView` to render different video tracks and I would think that we will change this in the future. In the meantime, the work around here is to create a new `TVIVideoView` for any `TVIVideoTrack`s that you wish to render.

Let me know if you are already waiting for the `videoViewDidReceiveData:` and are still receiving black frames after that call back is fired.

Thanks!

Ryan

**Comment by sathishvgs** [comment] 2018-03-15 11:34
Hi @paynerc ,

For me, videoViewDidReceiveData: delegate itself is not calling. I reusing the same views for rendering the videotracks

**Comment by paynerc** [comment] 2018-03-15 13:24
@sathishvgs Do you get it the first time you use the view? As I mentioned above, if you add the view to another track for rendering, you currently will not get `videoViewDidReceiveData:` on subsequent tracks.

Can you show me the code where you set the delegate on `TVIVideoView` and the implementation of `videoViewDidReceiveData:`?

Ryan

**Comment by sathishvgs** [comment] 2018-03-15 13:43
Hi @paynerc,

          Once user get into the application, I'm rendering the local video track in the main screen. If any participant joined the call, I'm just rendering the participant remote video track in the main screen. The local video track will go to some other separate view. 

So, in this case the videoViewDidReceiveData: will call ?

**Comment by sathishvgs** [comment] 2018-03-15 13:44
Hi @paynerc,

          Once user get into the application, I'm rendering the local video track in the main screen. If any participant joined the call, I'm just rendering the participant remote video track in the main screen. The local video track will go to some other separate view. 


So, in this case the videoViewDidReceiveData: will call ?

**Comment by sathishvgs** [comment] 2018-03-15 13:46
Hi @paynerc ,

Once user get into the application, I'm rendering the local video track in the main screen. If any participant joined the call, I'm just rendering the participant remote video track in the main screen. The local video track will go to some other separate view.

So, in this case the videoViewDidReceiveData: will call ?

**Comment by paynerc** [comment] 2018-03-15 14:16
@sathishvgs,

OK, so if my understanding is correct, you are just removing the `TVIVideoView` from the `TVILocalVideoTrack` by calling `removeRenderer:` when a remote participant joins the room and then invoking `addRenderer:` on the `TVIRemoteVideoTrack` passing in the same `TVIVideoView`?

If that is indeed the case, and you are reusing the same `TVIVideoView` instance, you will not receive another `videoViewDidReceiveData:` callback when video frames are received from the remote video track. As I mentioned previously, this is a currently known issue in our SDK.

However, even with that limitation in mind, I think you would still suffer from this issue in your current implementation. Once the track is subscribed, that means that you have negotiated the media connection and are ready to receive data across that connection. But it still takes some time until you have the first actual frame of video.

So if you are wanting to display that remote video track in the main view, and you make that switch on the subscribed call back, you will still be rendering black frames until the data is available.

A possible suggestion for the use case I believe you are describing it that when you receive a subscription event, create another `TVIVideoView` with the same dimensions as your main `TVIVideoView`, , set the delegate, make it hidden, add it to your view hierarchy behind your main view and add it as a renderer to the remote video track.

When you receive the `videoViewDidReceiveData:` callback on this new remote participant video view, you would unhide it and remove your current video view that is showing local video. This would ensure that when you show the new view for the remote video track, you are doing so when it actually has data to show.

Ryan

**Comment by sathishvgs** [comment] 2018-03-15 14:31
@paynerc,

      I will give a try on this. Can I know when this issue will fully resolve ?

**Comment by sathishvgs** [comment] 2018-03-15 14:31
@paynerc ,
      I will give a try on this. Can I know when this issue will fully resolve ?

**Comment by paynerc** [comment] 2018-03-15 14:35
@sathishvgs,

As I mentioned, I don't believe in your current use case the fix to the limitation where `videoViewDidReceiveData:` is only ever called once for a `TVIVideoView` is going to solve your issue. If you were to add the view to the remote data track before it has video data, you will still get the initial black frames. And then you would get the notification that data is available. But since you are swapping out which video track the view is rendering on the subscribe callback, you will already have done that before the data has been received.

With that said, I can post back on this ticket when we address that limitation.

Thanks,

Ryan

**Comment by ceaglest** [comment] 2018-03-15 17:46
Hey @sathishvgs,

It does sound like your issue is related to reusing TVIVideoView. My apologies for not diagnosing this in the previous issue that you filed. We have an internal ticket ISDK-1907 which is tracking this problem. We should be able to resolve it during the 2.0 beta period.

Best,
Chris

**Comment by sathishvgs** [comment] 2018-03-16 08:06
@paynerc @ceaglest ,

   Thank you for your kindly help. Looking forward this black frame fix in 2.0.

**Comment by paynerc** [comment] 2018-04-27 14:31
@sathishvgs,

Just wanted to let you know that we release `2.0.0` yesterday and it includes changes to `TVIVideoView`. Now when you remove the view as a renderer for a video track, the view gets set back to it's original state. The last frame is removed, the internal view is resized allowing it to be completely transparent and you will get the `videoViewDidReceiveData:` callback when the view has a video frame to display.

Please try this out and let me know if that helps solve your issue.

Thanks!

Ryan

**Comment by sathishvgs** [comment] 2018-05-17 11:08
Hi @paynerc ,

I have updated to 2.0.0. Here, I found one strange behaviour where the **videoViewDidReceiveData:** is calling repeatedly once I set the delegate for TVIVideo. 

Note: I have commented all the **hasVideoData** condition.

One more thing I need to know is why  **videoViewDidReceiveData:** is calling if I check the **hasVideoData** condition.

**Comment by paynerc** [comment] 2018-05-18 18:58
@sathishvgs,

Any time a `TVIVideoView` is reused, we will reset the `hasVideoData` property back to `no` until the view is reused and the first frame is received from the new track. When that first frame hits, we will set `hasVideoData` back to `YES` and will fire the `videoViewDidReceiveData:` delegate method.

Do you have sample code that reproduces this issue where `videoViewDidReceiveData:` is being called repeatedly and when inspecting the `hasVideoData` property is causing the `videoViewDidReceiveData:` delegate method to be called? I am not observing this behavior locally.

Thanks!

Ryan

**Comment by sathishvgs** [comment] 2018-05-25 13:49
Hi @paynerc ,
  Its working fine but I need to find which participants frame the **videoViewDidReceiveData:** is triggering. Currently, **videoViewDidReceivedData:** giving only TVIVideoView. If it gives that particular **TVIRemoteParticipant** instance we can find which participants frame currently we got.

Is there any solution for this ??

**Comment by paynerc** [comment] 2018-05-25 15:28
@sathishvgs,

OK, so when you say you are getting `videoViewDidReceiveData:` multiple times, you mean you are getting it invoked for different `TVIVideoView`s and not multiple times for a given `TVIVideoView`. If that is the case, then that makes more sense to me.

So there are a few ways to handle this. The `TVIVideoView` has no ties to the `TVIRemoteParticipant` that it is rendering. That would be very tight coupling between layers of the SDK that I don't feel is something that we want to be doing within the SDK.

The way that I handle this in our internal video app is that I have a model class that contains my remote participant and some other properties. That model class is then provided as a property to the  `UICollectionViewCell` subclass that is configured to render the participant video. That UICollectionViewCell is the class that implements the `TVIVideoViewDelegate` methods. When the delegate method is invoked, it is fired for the `TVIVideoView` that is in that `UIColletionViewCell`s view hierarchy.

I hope that helps. Let me know if you have any further questions.

Ryan

**Comment by paynerc** [comment] 2018-10-03 16:34
@sathishvgs,

Its been awhile since I have heard from you and I assume that you have moved past this issue? I am going to close this issue, but feel free to open it again if you have further issues related to this.

Thanks,

Ryan

**Closed by paynerc** 2018-10-03 16:34 UTC
