### ISSUE TITLE
Consistently crashing on iOS 10.0 betas

### ISSUE THREAD

**Issue by JRG-Developer** [twilio/video-quickstart-swift#43] opened 2016-10-25 18:55 UTC
I'm consistently getting a crash whenever I run this example on a physical iPhone 6s Plus running iOS 10.0.

Here's the info for reproducing the crash.

I'm using the following:
- Xcode v. 8.0 (8A21a)
- CocoaPods v. 1.1.0.rc.2
- iPhone 6s Plus running iOS v. 10.0 (14A5346a)

Steps to reproduce:
1. Clone the Video Quick Start Swift repo.
2. Do `pod install`.
3. Generate a new access token via the console testing tools (we already have an existing configuration profile), naming the client identity "Alice" per the README suggestion.
4. Open `VideoQuickStart.xcworkspace` in Xcode.
5. Change the bundle identifier to `com.mycompany.VideoQuickStart` and the team to `My Team Name` on the `VideoQuickStart` target; otherwise, the project won't code sign correctly for the physical device. (I don't think this is significant, but I'm including this step here for completeness.)
6. Set the `accessToken` to the generated token from step 2.
7. Build and run.
8. Note the app consistently crashes when the line around 139 in `ViewController.swift` is called:

```
localVideoTrack = localMedia?.addVideoTrack(true, capturer: camera!)
```

This gives generic reason `EXC_BAD_ACCESS(code=1, address=0x0)`.

Per the stack track trace (see image), it appears this may be related to calling `[TWCDeviceFormatUtilities videoCaptureDeviceForSource:]` in the underlying Objective-C code.

![iphone6splus_crash_stack_trace](https://cloud.githubusercontent.com/assets/2283896/19699670/da84f708-9ab9-11e6-8d58-242800990f68.png)

I also tried the Objective-C version of this quick start (following the same steps listed above), and I get the same crash whenever the equivalent line in Objective-C is called:

```
self.localVideoTrack = [self.localMedia addVideoTrack:YES capturer:self.camera];
```

I suspect this is an issue within the underlying `TwilioVideo` library, not the demos.

**Comment by ceaglest** [comment] 2016-10-25 19:16
@JRG-Developer thanks for filing an issue. You are correct to assume that the problem is in the `TwilioVideo.framework`, and not the example code. We will look into this issue and reply once it is solved.

**Comment by ceaglest** [comment] 2016-10-25 22:24
@JRG-Developer I was able to reproduce this issue using any physical device running the iOS 10.0 betas. What happened is Apple introduced changes to their AVFoundation APIs along with the GM of iOS 10.0. Since we wanted to support the telephoto lens on the iPhone 7 Plus, and explicitly disable wide-color support we opted into these new AVCaptureSession / AVCaptureDevice APIs. Internally, we use a compatibility check like:

```
    // Use modern APIs
    if ([[NSProcessInfo processInfo] isOperatingSystemAtLeastVersion:(NSOperatingSystemVersion){10, 0, 0}]) {
```

Unfortunately on beta devices this check succeeds, but the GM APIs don't actually exist - causing the crash you experienced. A safer way to do this internally would be an additional selector check. I will attempt to make this change for our `beta2` release, but I can't promise that it will be done in time.

Thanks for writing in, I'll leave this issue open for now and close if we land the stability improvement in a future release.

**Comment by JRG-Developer** [comment] 2016-10-26 15:54
@ceaglest Thanks for the feedback on this. Ah, you're right... this iOS version _is_ a beta.

We'll update our device to the latest, production iOS 10 version.

If this is happening _only_ on the betas (unfortunately, we have limited devices we can test against that are running iOS 10), we're cool with this issue being closed.

That is, iOS 10 betas shouldn't be on customers' devices, so it's cool with us if this simply isn't supported.

👍

**Comment by JRG-Developer** [comment] 2016-10-26 15:58
Yes, I agree that a selector check is a good idea here too.

In general, we prefer this in our own code bases instead of checking versions, which as you found, can be dangerous...! 😉 

Thanks!

**Comment by ceaglest** [comment] 2016-11-03 16:45
I added a known issue to our [changelog](https://www.twilio.com/docs/api/video/changelogs/ios). Closing this ticket.

**Comment by ceaglest** [comment] 2016-12-13 21:49
@JRG-Developer we ended up fixing this crash in `1.0.0-beta4`, just in time for the iOS 10.2 release. :)

We will be more careful in the future about conditional OS version checks.

**Closed** 2016-12-15 07:25 UTC
