### ISSUE TITLE
(2.0.0-preview7) Crash after another user disconnects

### ISSUE THREAD

**Issue by magneticrob** [twilio/video-quickstart-swift#210] opened 2017-11-28 10:38 UTC
### Description

When leaving and joining a conversation (with only a voice audio track, no video), the app can crash.

### Steps to Reproduce

1. Create a Room, join it with only an audio track
2. Allow another user to join it
3. Make that other user leave
4. Repeat until you experience a crash

#### Code

I am using pretty much the video-quickstart code here.

#### Expected Behavior

Most times it works fine. I would expect it to happen the same way every time.

#### Actual Behavior

The app crashes.

#### Reproduces How Often

It took me about 4-5 tries. You have to do it repeatedly.

#### Logs

The app crashes with the following error: 

"libc++abi.dylib: terminating with uncaught exception of type std::__1::bad_weak_ptr: bad_weak_ptr

ERROR:TwilioVideo:[Signaling]:RESIP::TRANSPORT: Got TLS read ret=0 error=6 error:00000006:invalid library (0):OPENSSL_internal:public key routines"

and stack trace:

Thread 134 Queue : room.worker (serial)
#0	0x0000000183dd5348 in __pthread_kill ()
#1	0x0000000183ee9344 in pthread_kill$VARIANT$mp ()
#2	0x0000000183d44fb8 in abort ()
#3	0x00000001834e4068 in abort_message ()
#4	0x00000001834e41f8 in default_terminate_handler() ()
#5	0x000000018350c820 in _objc_terminate() ()
#6	0x00000001834fc54c in std::__terminate(void (*)()) ()
#7	0x00000001834fbea8 in __cxa_throw ()
#8	0x0000000105e4d330 in twilio::signaling::RoomSignalingImpl::processParticipantsMessage(std::__1::vector<twilio::signaling::ServerStateMessage::RemoteParticipant, std::__1::allocator<twilio::signaling::ServerStateMessage::RemoteParticipant> > const&, twilio::signaling::ServerMessageBase::Type) ()
#9	0x0000000105e4b8ac in twilio::signaling::RoomSignalingImpl::processServerStateMessage(twilio::signaling::ServerStateMessage const*) ()
#10	0x0000000105e4b74c in twilio::signaling::RoomSignalingImpl::onRoomMessageSerial(twilio::signaling::ServerMessageBase*) ()
#11	0x0000000105e539e0 in rtc::ClosureTask<rtc::MethodFunctor1<twilio::signaling::RoomSignalingImpl, void (twilio::signaling::RoomSignalingImpl::*)(twilio::signaling::ServerMessageBase*), void, twilio::signaling::ServerMessageBase*> >::Run() ()
#12	0x0000000105af011c in rtc::TaskQueue::TaskContext::RunTask(void*) ()
#13	0x000000010a75545c in _dispatch_client_callout ()
#14	0x000000010a764110 in _dispatch_queue_serial_drain ()
#15	0x000000010a7589a4 in _dispatch_queue_invoke ()
#16	0x000000010a765104 in _dispatch_root_queue_drain_deferred_wlh ()
#17	0x000000010a76c100 in _dispatch_workloop_worker_thread ()
#18	0x0000000183ee6fd0 in _pthread_wqthread ()
#19	0x0000000183ee6c20 in start_wqthread ()

#### Video iOS SDK

TwilioVideo 2.0.0-preview7

#### Xcode

Version 9.1 (9B55)

#### iOS Version

11.1.2, but have experienced it on iOS10 and other iOS11 versions

#### iOS Device

iPhone 7, but have experienced it on other devices

**Comment by ceaglest** [comment] 2017-11-28 18:14
Hi @magneticrob,

Thanks for the report! We will reproduce this issue locally and then look into how to resolve it.

Best,
Chris Eagleston.

**Comment by ceaglest** [comment] 2017-12-01 20:19
Quick update - we can reproduce the same issue locally in our integration tests and are looking into a fix for the crash.

**Comment by ceaglest** [comment] 2017-12-08 23:14
Hi,

One more update - the bug has now been fixed in our C++ layer and is undergoing internal testing. We will include it in the 2.0.0-preview8 release, which we hope to publish by the end of next week.

A temporary workaround to reduce or eliminate the crash is to call disconnect() on the Room and wait for it to complete before destroying the object. Thanks again for reporting this problem!

Regards,
Chris Eagleston

**Comment by ceaglest** [comment] 2018-01-05 22:50
Hello again,

We didn't get our next release with this bug fix out before the holiday break. Now that our teams are back in the office we expect to ship 2.0.0-preview8 next week.

Thanks again for reporting the bug, and sorry for the delay in getting out a fix.

Regards,
Chris Eagleston

**Comment by magneticrob** [comment] 2018-01-08 11:19
Thanks for the update Chris - really appreciate the work you lot are doing on this.

Cheers

Rob

**Comment by ceaglest** [comment] 2018-01-10 00:28
Hey @magneticrob,

We've just released [2.0.0-preview8](https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x#200-preview8-january-9-2018) which should resolve any occurrences of this crasher. Please give it a try when you get the chance.

Thanks for your patience,
Chris Eagleston

**Comment by ceaglest** [comment] 2018-01-13 01:16
Closing this issue, since the bug should now be fixed.

**Closed by ceaglest** 2018-01-13 01:16 UTC
Labels: bug

**Comment by sathishvgs** [comment] 2018-04-05 16:08
Hi @magneticrob ,
               How would you fixed the issue. Currently, I'm facing this same issue. Can you help me to fix.

**Comment by ceaglest** [comment] 2018-04-05 16:09
Hi @sathishvgs,

What version of our SDK are you using? The bug reported here was fixed in 2.0.0-preview8.

Chris

**Comment by magneticrob** [comment] 2018-04-05 16:19
@sathishvgs yep, as @ceaglest said, I found this bug in 2.0.0-preview7 and it was fixed in 2.0.0-preview8.

**Comment by sathishvgs** [comment] 2018-04-06 15:57
@ceaglest , @magneticrob 

     I'm using twilio preveiw 2.0.0-beta 3. For me, the issue is occurring sometimes.

     @magneticrob How long it takes to connect a call approximately ?

**Comment by ceaglest** [comment] 2018-04-06 16:06
Hi @sathishvgs,

Unless you are seeing the same crashing call stack, I think this is a different issue than what was fixed in 2.0.0-preview8. Would you mind opening a new issue, and sharing the call stack and reproduction steps with us?

Thanks,
Chris

**Comment by sathishvgs** [comment] 2018-04-06 16:15
Hi @ceaglest ,
   I have opened the #252 .

**Comment by ceaglest** [comment] 2018-04-06 16:16
I'm confused then, since #252 is about not being able to connect to a Room. I didn't see any mention of a crash.

**Comment by sathishvgs** [comment] 2018-04-06 16:25
Hi @ceaglest ,
  It showed the same error message but not crashed. Let we stop here and start follow the issue #252 .
