### ISSUE TITLE
*** Terminating app due to uncaught exception 'TVIAudioDeviceMustBeSetBeforeMediaStackSetup', reason: 'WebRTC does not allow updating the audio device once the media stack is created (i.e once a track is created or memory allocated for previously created room or connect option is not deleted). You should provide the audio device to SDK prior to creating the tracks.'

### ISSUE THREAD

**Issue by FahadAlbukhari** [twilio/video-quickstart-swift#230] opened 2018-02-21 20:14 UTC
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Github Issues](https://github.com/twilio/video-quickstart-swift/issues)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelogs/ios)

### Description

After I disconnect to the room and dismiss the view, every thing is fine. When I show the view agin, I gat this error *** Terminating app due to uncaught exception 'TVIAudioDeviceMustBeSetBeforeMediaStackSetup', reason: 'WebRTC does not allow updating the audio device once the media stack is created (i.e once a track is created or memory allocated for previously created room or connect option is not deleted). You should provide the audio device to SDK prior to creating the tracks.'

#### Logs

2018-02-21 13:52:01.507354-0600[2137:734610] Attempting to disconnect from room uy7fkm
2018-02-21 13:52:01.508966-0600[2137:734649] EndCallAction transaction request successful
2018-02-21 13:52:01.511336-0600[2137:734610] provider:performEndCallAction:
2018-02-21 13:52:01.757742-0600[2137:734610] provider:didDeactivateAudioSession:
2018-02-21 13:52:02.237582-0600[2137:734610] Disconncted from room uy7fkm, error = nil
2018-02-21 13:52:03.826919-0600[2137:734649] StartCallAction transaction request successful
2018-02-21 13:52:03.834518-0600[2137:734610] *** Terminating app due to uncaught exception 'TVIAudioDeviceMustBeSetBeforeMediaStackSetup', reason: 'WebRTC does not allow updating the audio device once the media stack is created (i.e once a track is created or memory allocated for previously created room or connect option is not deleted). You should provide the audio device to SDK prior to creating the tracks.'
*** First throw call stack:
(0x18262b164 0x181874528 0x18262ae2c 0x104f1898c 0x104f0e500 0x104849720 0x10484a0d8 0x18bbe5a00 0x18bbe55d8 0x18c78ed24 0x18bf2da18 0x18bf5e84c 0x18bf6176c 0x18bf61ca0 0x18bf616bc 0x18bcc32d0 0x1a1866358 0x18bf65578 0x18c39bc64 0x18c50b0b0 0x18c50af54 0x18bf55870 0x1a18670e4 0x104870988 0x1048709f8 0x18bc1a5cc 0x18bc1a54c 0x18bc050f4 0x18bc19e40 0x18bc19960 0x18bc14e78 0x18bbe5e7c 0x1a181a780 0x18c53b30c 0x18c53d898 0x18c5367b0 0x1825d377c 0x1825d36fc 0x1825d2f84 0x1825d0b5c 0x1824f0c58 0x18439cf84 0x18bc495c4 0x10485b784 0x18201056c)
libc++abi.dylib: terminating with uncaught exception of type NSException

### Versions

All relevant version information for the issue.

#### Video iOS SDK
'TwilioVideo', '2.0.0-beta1'

#### Xcode
Version 9.3 beta 2 (9Q107o)

#### iOS Version
11.2.5

#### iOS Device
iPhone X

**Comment by paynerc** [comment] 2018-02-21 20:51
Hello there,

From the message you are reporting, it appears that our internal media factory is still alive when you are attempting to set up the audio device a second time. This is the case if the `TVIRoom`, `TVILocalAudioTrack` or `TVIConnectOptions` are still around after you have disconnected from the room.

Can you verify that you have no references to `TVIRoom`, `TVILocalAudioTrack` or `TVIConnectOptions` before you are setting the audio device?

Thanks,

Ryan

**Comment by FahadAlbukhari** [comment] 2018-02-21 21:02
Thank you for quick response. I have



    func provider(_ provider: CXProvider, perform action: CXEndCallAction) {
        NSLog("provider:performEndCallAction:")

        // AudioDevice is enabled by default
        self.audioDevice.isEnabled = true
        room?.disconnect()
        
        
        self.camera = nil
        self.localAudioTrack = nil
        self.localVideoTrack = nil
        self.remoteParticipant = nil
        self.remoteView = nil
        self.room = nil
        
        action.fulfill()
    }

$$$$$$$$$$$$$$$$$$ Connect $$$$$$$$$$$$$$$$$$
2018-02-21 14:54:20.509794-0600[2240:762638] StartCallAction transaction request successful
2018-02-21 14:54:20.571214-0600[2240:762582] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2018-02-21 14:54:20.572006-0600[2240:762582] [MC] Reading from public effective user settings.
2018-02-21 14:54:20.595594-0600[2240:762582] Video track created
2018-02-21 14:54:20.598043-0600[2240:762582] providerDidBegin
2018-02-21 14:54:20.598226-0600[2240:762582] provider:performStartCallAction:
2018-02-21 14:54:20.690292-0600[2240:762582] provider:didActivateAudioSession:
2018-02-21 14:54:20.868093-0600[2240:762582] Attempting to connect to room Optional("")
2018-02-21 14:54:22.163998-0600[2240:762582] Connected to room uy7fkm as Optional("fulw09")

$$$$$$$$$$$$$$$$$$ Disconnect $$$$$$$$$$$$$$$$$$

2018-02-21 14:54:31.695680-0600[2240:762582] Attempting to disconnect from room uy7fkm
2018-02-21 14:54:31.697939-0600[2240:762790] EndCallAction transaction request successful
2018-02-21 14:54:31.703312-0600[2240:762582] provider:performEndCallAction:
2018-02-21 14:54:32.312396-0600[2240:762582] provider:didDeactivateAudioSession:




$$$$$$$$$$$$$$$$$$ Connect Agin $$$$$$$$$$$$$$$$$$

2018-02-21 14:54:37.699270-0600[2240:762639] StartCallAction transaction request successful
2018-02-21 14:54:37.714588-0600[2240:762582] Video track created
2018-02-21 14:54:37.718197-0600[2240:762582] providerDidBegin
2018-02-21 14:54:37.718729-0600[2240:762582] provider:performStartCallAction:
2018-02-21 14:54:37.819120-0600[2240:762582] provider:didActivateAudioSession:
2018-02-21 14:54:37.931497-0600[2240:762582] Video track created
2018-02-21 14:54:37.966188-0600[2240:762582] Attempting to connect to room Optional("")
2018-02-21 14:54:39.059458-0600[2240:762582] Connected to room uy7fkm as Optional("fulw09")

$$$$$$$$$$$$$$$$$$ Disconnect Agin $$$$$$$$$$$$$$$$$$
No LOG

$$$$$$$$$$$$$$$$$$ Connect Agin $$$$$$$$$$$$$$$$$$
2018-02-21 14:54:47.080444-0600[2240:762582] *** Terminating app due to uncaught exception 'TVIAudioDeviceMustBeSetBeforeMediaStackSetup', reason: 'WebRTC does not allow updating the audio device once the media stack is created (i.e once a track is created or memory allocated for previously created room or connect option is not deleted). You should provide the audio device to SDK prior to creating the tracks.'
*** First throw call stack:
(0x18262b164 0x181874528 0x18262ae2c 0x104be498c 0x104bda500 0x1045388d0 0x104539288 0x18bbe5a00 0x18bbe55d8 0x18c78ed24 0x18bf2da18 0x18bf5e84c 0x18bf6176c 0x18bf61ca0 0x18bf616bc 0x18bcc32d0 0x1a1866358 0x18bf65578 0x18c39bc64 0x18c50b0b0 0x18c50af54 0x18bf55870 0x1a18670e4 0x10455ff44 0x10455ffb4 0x18bc1a5cc 0x18bc1a54c 0x18bc050f4 0x18bc19e40 0x18bc19960 0x18bc14e78 0x18bbe5e7c 0x1a181a780 0x18c53b30c 0x18c53d898 0x18c5367b0 0x1825d377c 0x1825d36fc 0x1825d2f84 0x1825d0b5c 0x1824f0c58 0x18439cf84 0x18bc495c4 0x10454a934 0x18201056c)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by piyushtank** [comment] 2018-02-23 06:17
@FahadAlbukhari  In order to debug the problem further can you answer following - 
are you waiting for the `room:didDisconnectWithError` call back before setting the `TwilioVideo.audioDevice`? Is it possible for you to share the code on how you are resetting the audio device?

**Comment by FahadAlbukhari** [comment] 2018-02-23 21:16
func room(_ room: TVIRoom, didDisconnectWithError error: Error?) {
        logMessage(messageText: "Disconncted from room \(room.name), error = \(String(describing: error))")
        
        self.cleanupRemoteParticipant()
        self.room = nil
        self.showRoomUI(inRoom: false)
        self.callKitCompletionHandler = nil
    }




    func provider(_ provider: CXProvider, perform action: CXEndCallAction) {
        NSLog("provider:performEndCallAction:")

        // AudioDevice is enabled by default
        self.audioDevice.isEnabled = true
        room?.disconnect()
        
        self.audioDevice = TVIDefaultAudioDevice()
        self.connectOptions = nil
        self.camera = nil
        self.localAudioTrack = nil
        self.localVideoTrack = nil
        self.remoteParticipant = nil
        self.remoteView?.removeFromSuperview()
        self.remoteView = nil
        self.room = nil
        TwilioVideo.audioDevice = TVIDefaultAudioDevice()
        accessToken = "TWILIO_ACCESS_TOKEN"
        
        


        
        self.callKitCompletionHandler = nil
        
        action.fulfill()
    }



Is this what are you looking for?

**Comment by piyushtank** [comment] 2018-02-23 21:42
@FahadAlbukhari Thanks for sharing the code.

1. If you are not doing any custom audio settings in your app you don't really need to set an audioDevice on SDK. The SDK will set the `audioDevice` at an appropriate time during the lifecycle of the call.

2. If you want to set the `audioDevice` explicitly on TwilioVideo, `func provider(_ provider: CXProvider, perform action: CXEndCallAction)` is not the right place, because TVIRoom does not get destroyed until `func room(_ room: TVIRoom, didDisconnectWithError error: Error?)` finish its execution. 
I would recommend following - 

```
func room(_ room: TVIRoom, didDisconnectWithError error: Error?) {
    logMessage(messageText: "Disconncted from room \(room.name), error = \(String(describing: error))")
    
    self.cleanupRemoteParticipant()
    self.room = nil
    self.showRoomUI(inRoom: false)
    self.callKitCompletionHandler = nil
}

func provider(_ provider: CXProvider, perform action: CXEndCallAction) {
    NSLog("provider:performEndCallAction:")

    // AudioDevice is enabled by default
    self.audioDevice.isEnabled = true
    room?.disconnect()
    
    self.audioDevice = TVIDefaultAudioDevice()
    self.connectOptions = nil
    self.camera = nil
    self.localAudioTrack = nil
    self.localVideoTrack = nil
    self.remoteParticipant = nil
    self.remoteView?.removeFromSuperview()
    self.remoteView = nil
    accessToken = "TWILIO_ACCESS_TOKEN"
    
    self.callKitCompletionHandler = nil
    
    action.fulfill()
}

func provider(_ provider: CXProvider, perform action: CXStartCallAction) {
   TwilioVideo.audioDevice = self.audioDevice;
   // other code..
}

func provider(_ provider: CXProvider, perform action: CXAnswerCallAction) {
   TwilioVideo.audioDevice = self.audioDevice;
   // other code..
}
```

3. Another solution is moidfy `func room(_ room: TVIRoom, didDisconnectWithError error: Error?)` to set audio device asynchronously on main thread.

```
func room(_ room: TVIRoom, didDisconnectWithError error: Error?) {   
     //.. other code
     self.room = nil;
     self.connectOptions = nil;
     self.localAudioTrack = nil;
     self.localVideoTrack = nil;
     DispatchQueue.main.async {
            self.audioDevice = TVIDefaultAudioDevice();
            TwilioVideo.audioDevice = self.audioDevice;
        }
}
```

Let me know if you have any questions.

**Comment by piyushtank** [comment] 2018-02-24 08:03
@FahadAlbukhari From logs ^ it seems you are creating a `TVILocalVideoTrack` prior to setting the `TwilioVideo.audioDevice`. Can you make sure video audioDevice getting set prior to creating video track?

```2018-02-24 00:15:18.822647-0600 ########[4147:1489484] Disconncted from room , error = nil
2018-02-24 00:15:19.399474-0600 ########[4147:1489527] StartCallAction transaction request successful
2018-02-24 00:15:19.411382-0600 ########[4147:1489484] Video track created
2018-02-24 00:15:19.418688-0600 ########[4147:1489484] providerDidBegin
2018-02-24 00:15:19.419136-0600 ########[4147:1489484] provider:performStartCallAction:
2018-02-24 00:15:19.419493-0600 ########[4147:1489484] *** Terminating app due to uncaugh
```

If ^ does not solve the problem, can you share a branch off our Quickstart sample app reproducing the problem?

**Comment by FahadAlbukhari** [comment] 2018-02-24 21:18
https://github.com/FahadAlbukhari/KhususiyVideoCallKitQuickStart.git

**Comment by piyushtank** [comment] 2018-02-25 22:10
@FahadAlbukhari I looked into your app and I was able to reproduce the problem. I have submitted a PR to your app with the fix : [link](https://github.com/FahadAlbukhari/KhususiyVideoCallKitQuickStart/pull/1)

While working on this, I have noticed a few other issues:

1. The app is leaking an `ViewController` object everytime you connect to a Room and go back to the CallViewController. Take a look - 
<img width="249" alt="screen shot 2018-02-25 at 1 51 21 pm" src="https://user-images.githubusercontent.com/17037593/36647013-252bf8d8-1a34-11e8-9f2b-5dc7dca87d22.png">

I would recommend, embed the view controllers into a navigation view controller and use push and pop view controller to eliminate the leak.

2. The token server information is publically available in your app : [token server](https://github.com/FahadAlbukhari/KhususiyVideoCallKitQuickStart/blob/master/Khususiy/ViewController.swift#L84). I am not sure if it is intended because anyone can see your repo and get the token from your token server.

Let me know if you have questions.

**Comment by FahadAlbukhari** [comment] 2018-02-25 23:41
Thank you for your help. I mad update to the code could you please review it (https://github.com/FahadAlbukhari/KhususiyVideoCallKitQuickStart.git). when I deploy the code to my app I get the problem agin. What do you mean by " The app is leaking an ViewController object everytime you connect to a Room and go back to the CallViewController. Take a look -"

**Comment by piyushtank** [comment] 2018-02-26 00:50
@FahadAlbukhari Do the following - 
1. Remove [this](https://github.com/FahadAlbukhari/KhususiyVideoCallKitQuickStart/blob/master/Khususiy/CallViewController.swift#L16) and [this](https://github.com/FahadAlbukhari/KhususiyVideoCallKitQuickStart/blob/master/Khususiy/CallViewController2.swift#L16)

2. Do `TwilioVideo.audioDevice = TVIDefaultAudioDevice()`  in MainViewController's `[ViewDidLoad()](https://github.com/FahadAlbukhari/KhususiyVideoCallKitQuickStart/blob/master/Khususiy/MainViewController.swift#L14)`

For ViewController's leak, I noticed, every time when you goto`ViewController` from `CallViewController` or `CallViewController2`, your app creates a new `ViewController` object, however, when you go back to 
`CallViewController` or `CallViewController2` from `ViewController` it does not delete the `ViewController` object. It's leaking the `ViewController`.

Can we close this ticket if the problem is resolved with Video SDK?

**Closed** 2018-02-26 01:22 UTC

**Comment by FahadAlbukhari** [comment] 2018-02-26 01:24
The solution: 
 TwilioVideo.audioDevice = TVIDefaultAudioDevice() has to be in the first ViewController of the app

**Comment by aksthelion** [comment] 2019-04-03 23:32
I'm also facing similar issue. I can't figure out the solution. Can anyone explain me  how to fix this issue?

**Comment by hdinhof1** [comment] 2020-08-25 19:03
Make sure your `deinit { }` is called. Had the same issue and had to use the memory debugger to figure it out. For me it happened with first-time use, during camera and microphone permissions, I created an extra reference to the VideoChatViewController. The extra reference was caused from a hidden call from `func applicationDidBecomeActive()`.   
TIL that system permissions prompts also call didBecomeActive.
