### ISSUE TITLE
VideoTracks not showing while joining from iOS to Chrome 7[Mac]

### ISSUE THREAD

**Issue by sathishvgs** [twilio/video-quickstart-swift#361] opened 2019-02-22 15:14 UTC
> Before filing an issue please check that the issue is not already addressed by the following:
> 
> * [Video Guides](https://www.twilio.com/docs/api/video)
> * [Changelog](https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x).
> 
> If this is an issue with the QuickStart itself, file it here. If this is an issue with the SDK or how to do something with the SDK please use [twilio-video-ios](https://github.com/twilio/twilio-video-ios/issues) instead.

**Description:**

Participants video not showing on my Mac browser. I have joined the room from iOS to Chrome 7 [Mac]. I got the participants Audio track but the **_Video track alone not showing in browser_**.

**Scenario:**
1. Local Participant L creates the room from iOS.
2. Remote Participant R1 joined the room from Chrome 7 [Mac]
3. Room is connected and both subscribed their Video and Audio tracks.
4. Local Participant L got the Video and Audio tracks who joined from iOS
5. **Remote Participant R1 who joins from Mac got the AudioTrack but didn't get the VideoTrack .**

**Things to note:**
1. If both the participant joins the call from Mobile [either iOS or Android], it works fine with Audio and Video tracks.

> Note: The issue is happening only from iOS to Web.

**Expected behaviour:**
If the participant joins the room from any device or Machine, the Audio and Video track should work.

**Reproduce:**
100% percentage Reproducible.

**Versions:**

Twilio iOS sdk version     -        2.7.0
Twilio Js   sdk version     -        1.15.2

iOS - 12.1.4
Browser - Chrome 7

**Comment by ceaglest** [comment] 2019-02-23 01:20
Hi @sathishvgs,

Can you please provide a Room SID (query the `Room.sid` property) where you experienced the Video Track not showing in your browser?

> Browser - Chrome 7

I'm not entirely clear, did you mean Chrome 70, 71, or 72? I can also gather this from the Room SID if needed.

Thanks,
Chris

**Comment by sathishvgs** [comment] 2019-02-23 03:01
Hi @ceaglest ,

Here is the Info,

Room SID  -> RMeb3e8a75d2b78db4f8e86c3d39d564e8
Browser     -> Chrome 72

**Comment by sathishvgs** [comment] 2019-02-25 15:20
Hi @ceaglest ,

Can you please give any solution for this. We are waiting for last two days and our users also complaining about this issue.

**Comment by ceaglest** [comment] 2019-02-26 00:39
Hi @sathishvgs,

I'm looking at this issue with @manjeshbhargav (cross-link: https://github.com/twilio/twilio-video.js/issues/551).

> Twilio iOS sdk version - 2.7.0
> iOS - 12.1.4
> Twilio Js sdk version - 1.15.2
> Browser -> Chrome 72
> Room SID -> RMeb3e8a75d2b78db4f8e86c3d39d564e8

In the Room SID that you provided, the Chrome Participant (using **2.0.0-beta5**) connects first and begins to publish audio/video Tracks. About 20 seconds later the iOS Participant connects with audio and video shared. ICE connectivity seems to take a long time (>10s) to be established but eventually completes.

The iOS Participant continues to send audio and video for the next ~25 seconds before disconnecting. The Chrome Participant also receives video (and audio) from the media server (1,371,900 bytes of VP8), and sends 11 Nacks, but zero PLIs during this time.

> 100% percentage Reproducible.

Is it reproducible for you using the Quickstart for twilio-video.js? Since there were bytes received I was wondering if there is an issue in your application code about handling subscription events? You mentioned that you were using 1.x which doesn't have subscription events, but 2.x (shown in your logs) does.

Best,
Chris

**Comment by ceaglest** [comment] 2019-02-26 00:52
Hi,

One more thought, does disabling simulcast on your Chrome Participant make any difference?

Regards,
Chris

**Comment by kamesh-a** [comment] 2019-02-26 05:42
Hello @ceaglest,

Thanks for your detailed input on this.

Thats right we are using two version of twilio for routing calls in different browsers context, to give an idea. In chrome 70+ we are using 2.0.0-beta5 experimenting with in house websocket signaling server from twilio for `SignalingIssues`

In our Electron based on desktop client we use 1x version which is `1.15.2`. As far as we have tested in IOS -> chrome video didn't show up , but as you said the I will recheck the subscription event logic and let me check with electron 1x. 

I will produce the results as well some debugging logs along with it.

**Comment by ceaglest** [comment] 2019-02-27 18:44
Hi,

Okay let me know how it goes. There is a pretty big difference between 1.x and 2.x for Javascript when it comes to handling Remote Tracks. There is a [migration guide](https://www.twilio.com/docs/video/migrating-1x-2x) which provides more information.

Cheers,
Chris

**Comment by kamesh-a** [comment] 2019-02-28 18:10
Hello @ceaglest,

Thanks for timely replies. Indeed we were receiving video tracks, due to a recent change  while switching libs, which we have missed few changes between iOS & browser.

thanks to @manjeshbhargav and you for pointing us in correct direction.

Please close this issue.

**Comment by ceaglest** [comment] 2019-02-28 18:15
I'm very glad to hear this! Take care, and don't hesitate to reach out if you have questions in the future.

**Closed by ceaglest** 2019-02-28 18:15 UTC
Labels: help wanted
